name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      ## Dependencies
      - name: Install Dependencies
        run: npm ci

      ## Lint
      - name: Run lint
        run: npm run lint

      ## Tests
      - name: Run tests
        run: npm run check

      ## Build
      - name: Build application
        run: npm run build
